apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"argocd"},"name":"etd-qa-storage"},"mountOptions":["hard","nfsvers=3","port=2049","timeo=120"],"parameters":{"fileSystemId":"bos-nfsisilon","server":"bos-nfsisilon.rc.fas.harvard.edu","share":"/ifs/bosisilon/huit/lts-docker-prod/k8-lzp/etdadm-qa"},"provisioner":"nfs.csi.k8s.io","reclaimPolicy":"Retain","volumeBindingMode":"Immediate"}
  creationTimestamp: '2024-10-11T19:51:05Z'
  labels:
    argocd.argoproj.io/instance: argocd
  managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:argocd.argoproj.io/instance: {}
        f:mountOptions: {}
        f:parameters:
          .: {}
          f:fileSystemId: {}
          f:server: {}
          f:share: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
      manager: argocd-controller
      operation: Update
      time: '2024-10-11T19:51:05Z'
  name: etd-qa-storage
  resourceVersion: '2631199'
  uid: 2709a12d-a299-492f-9d87-86fa4b22b2c9
mountOptions:
  - hard
  - nfsvers=3
  - port=2049
  - timeo=120
parameters:
  fileSystemId: bos-nfsisilon
  server: bos-nfsisilon.rc.fas.harvard.edu
  share: /ifs/bosisilon/huit/lts-docker-prod/k8-lzp/etdadm-qa
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
