allowVolumeExpansion: false
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    field.cattle.io/description: sanjsy sc
  creationTimestamp: '2024-10-12T18:41:10Z'
  managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/description: {}
        f:mountOptions: {}
        f:parameters:
          .: {}
          f:fileSystemId: {}
          f:server: {}
          f:share: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
      manager: rancher
      operation: Update
      time: '2024-10-12T19:07:02Z'
  name: etd-monitor-sc
mountOptions:
  - hard
  - nfsvers=3
  - port=2049
  - timeo=600
parameters:
  fileSystemId: bos-nfsisilon
  server: bos-nfsisilon.rc.fas.harvard.edu
  share: /etdadm-qa
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
