apiVersion: v1
kind: PersistentVolume
metadata:
    name: solr-dev-pv
    namespace: solroperator
    annotations:
        pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
    storageClassName: solr-dev-storage
    capacity:
        storage: 1Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    mountOptions:
        - nfsvers=4.1
    csi:
        driver: nfs.csi.k8s.io
        readOnly: false
        volumeHandle: solr-vol
        volumeAttributes:
            server: fs-05c115bda25dc9dd4.efs.us-east-1.amazonaws.com
            share: /