apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - mountPath: "/mnt/test"
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: etd-pvc